In [125]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

<b>1. Load .xlsx file to a pandas DataFrame.</b>

In [126]:
df = pd.read_excel('igrzyska.xlsx', sheet_name='t201223CRC')
df.head()

URODZONY  PLEC  KLM6  woj  q9  q10  q11  q12   q13  q14  ...  q153  q154  \
0      1940     2     1   11   2    4  NaN   13   8.0    1  ...   2.0     2   
1      1943     1     3   11   8    4  NaN   13   3.0    1  ...   NaN     2   
2      1936     1     3   11   8    4  NaN   13   3.0    1  ...   NaN     2   
3      1948     1     3   11   4    4  NaN   13   6.0    1  ...   2.0     2   
4      1994     2     1   10   3    4  NaN   11  11.0    2  ...   NaN     1   

   q155  q156  r7s1  r7s2  r7s3  r7s4  r7s5      waga  
0   NaN     2  2012     7     4    18    42  0.722004  
1   NaN     2  2012     7     4    16    43  0.686766  
2   NaN     1  2012     7     4    18    16  0.686766  
3   NaN     2  2012     7     4    19    43  1.604806  
4   2.0     1  2012     7     5    11    17  1.316088  

[5 rows x 266 columns]

<b>2. Create a column named 'error' containing prediction error between 'q93' column value and a real number of golden medals acquired by Poland on the 2012 Olympic Games.</b>

In [127]:
print('Number of not-NA values in column q93: \t {0}'.format(df['q93'].count()),
      '\nNumber of NA values in q93 column: \t {0}'.format(df['q93'].isna().count()),
      '\nq93 column median: \t\t\t {0}'.format(np.nanmedian(df['q93'])),
      '\nq93 column mean: \t\t\t {0}'.format(np.nanmean(df['q93'])))

df.loc[df['q93'].isna(), ['q93']] = np.nanmedian(df['q93'])
df['error'] = df['q93'] - 11
df['error']

Number of not-NA values in column q93: 	 692 
Number of NA values in q93 column: 	 960 
q93 column median: 			 10.0 
q93 column mean: 			 9.693641618497109


0     -4.0
1     -1.0
2     -1.0
3      3.0
4     -1.0
5     -1.0
6     -6.0
7     -1.0
8     -6.0
9     -1.0
10    -1.0
11    -6.0
12    -3.0
13    -6.0
14    -6.0
15     0.0
16    -4.0
17     0.0
18    -3.0
19    -1.0
20    -1.0
21    -1.0
22     4.0
23     1.0
24    -1.0
25    -1.0
26     1.0
27    -1.0
28    -1.0
29    -1.0
      ... 
930   -1.0
931   -1.0
932   -1.0
933   -1.0
934   -1.0
935   -1.0
936   -6.0
937   -1.0
938   -1.0
939    1.0
940    1.0
941   -4.0
942    1.0
943    1.0
944   -1.0
945   -7.0
946   -1.0
947    1.0
948   -1.0
949   -7.0
950   -7.0
951   -6.0
952    4.0
953   -6.0
954    4.0
955   -7.0
956    4.0
957    4.0
958   -6.0
959    0.0
Name: error, Length: 960, dtype: float64

<b>3. Count correct predictions and show the rows that describe them.</b>

In [128]:
print('Number of correct predictions: \t {0}'.format(df[df['q93'] == 11]['q93'].count()))
print(df[df['q93'] == 11]['q93'])
df[df['q93'] == 11]

Number of correct predictions: 	 30
15     11.0
17     11.0
172    11.0
197    11.0
217    11.0
274    11.0
291    11.0
300    11.0
309    11.0
334    11.0
354    11.0
438    11.0
508    11.0
539    11.0
544    11.0
574    11.0
593    11.0
602    11.0
604    11.0
639    11.0
670    11.0
683    11.0
702    11.0
789    11.0
790    11.0
809    11.0
826    11.0
914    11.0
917    11.0
959    11.0
Name: q93, dtype: float64


URODZONY  PLEC  KLM6  woj  q9  q10  q11  q12   q13  q14  ...  q154  q155  \
15       1936     1     5   13  12    4  NaN   13   2.0    1  ...     2   NaN   
17       1986     2     5   12  11    4  NaN   14   5.0    2  ...     2   NaN   
172      1988     2     1   13   8    2  3.0    5   NaN    2  ...     1   1.0   
197      1985     1     1    6   4    4  NaN    6   NaN    2  ...     1   1.0   
217      1969     1     1   15  10    1  3.0   10   NaN    1  ...     2   NaN   
274      1952     2     1    2   2    4  NaN   13   6.0    1  ...     1   3.0   
291      1968     1     3   16   4    1  3.0   10   NaN    2  ...     2   NaN   
300      1980     2     5   12  11    1  3.0    4   NaN    2  ...     2   NaN   
309      1960     2     1   11   4    4  NaN   16   6.0    2  ...     1   4.0   
334      1957     2     4    1  11    1  1.0    2   NaN    2  ...     2   NaN   
354      1991     1     4    5   8    1  2.0    5   NaN    2  ...     2   NaN   
438      1957     1     1   13   4    1  2.0    6   NaN    2  ...     2   NaN   
508      1983     2     4   12   7    2  1.0    5   NaN    2  ...     2   NaN   
539      1980     1     2   11   4    1  3.0    6   NaN    2  ...     2   NaN   
544      1961     1     5   12  11    1  1.0    2   NaN    2  ...     2   NaN   
574      1986     2     1    4   7    1  3.0    5   NaN    2  ...     1   4.0   
593      1973     2     4   12   9    4  NaN   15   4.0    2  ...     2   NaN   
602      1987     1     1   13   7    1  3.0   10   NaN    2  ...     2   NaN   
604      1991     2     5    6   8    4  NaN   11  11.0    2  ...     2   NaN   
639      1987     2     6    1   8    1  3.0    4   NaN    2  ...     2   NaN   
670      1973     2     5    9  12    1  1.0    2   NaN    2  ...     2   NaN   
683      1949     1     3    9   4    4  NaN   14   7.0    2  ...     2   NaN   
702      1978     2     5   12  11    1  3.0    1   NaN    2  ...     2   NaN   
789      1945     2     4   15   4    4  NaN   13   3.0    1  ...     2   NaN   
790      1974     2     3   12  11    1  1.0    2   NaN    2  ...     2   NaN   
809      1993     2     5   16   6    1  3.0    7   NaN    2  ...     2   NaN   
826      1985     2     6    1  11    1  3.0    2   NaN    2  ...     2   NaN   
914      1968     2     1    5  11    1  2.0    2   NaN    2  ...     2   NaN   
917      1980     1     2    2   4    1  3.0    6   NaN    2  ...     2   NaN   
959      1944     2     5   12   7    4  NaN   12   6.0    1  ...     2   NaN   

     q156  r7s1  r7s2  r7s3  r7s4  r7s5      waga  error  
15      1  2012     7     5    17    56  0.639548    0.0  
17      1  2012     7     5    18    29  0.525158    0.0  
172     2  2012     7     7    12    27  0.749091    0.0  
197     1  2012     7     7    14    52  1.772485    0.0  
217     1  2012     7     7    12    15  0.987732    0.0  
274     2  2012     7     7    14    11  0.631724    0.0  
291     1  2012     7     7    12    41  1.055805    0.0  
300     1  2012     7     7    17    21  0.811256    0.0  
309     1  2012     7     7    10    43  1.288454    0.0  
334     1  2012     7     5    16    47  1.243574    0.0  
354     1  2012     7     5    14    32  1.183139    0.0  
438     1  2012     7     9    11    58  0.928852    0.0  
508     1  2012     7     9    19     9  1.240262    0.0  
539     1  2012     7     9    16    44  1.198537    0.0  
544     1  2012     7     9    17    44  0.888639    0.0  
574     1  2012     7     9    20    41  0.788239    0.0  
593     1  2012     7     9    10     7  1.231075    0.0  
602     1  2012     7    10    11     5  1.258257    0.0  
604     1  2012     7     9    17    40  1.968662    0.0  
639     1  2012     7    10    17     3  1.117624    0.0  
670     1  2012     7    10    16    18  0.710589    0.0  
683     2  2012     7    10    17    36  0.828083    0.0  
702     1  2012     7    10    18    53  0.811256    0.0  
789     2  2012     7    10    11    10  1.093791    0.0  
790     1  2012   

<b>4. Draw plots visualizing prediction value change over the year of the responder.</b>

In [129]:
# TO-DO: do this! (bar charts and many more)

<b>5. Check correlation between prediction error column and column containing job group of the responder.</b>

In [130]:
print('=== Correlation measures between error column and gender column ===',
      '\nPearson method: \t {0}'.format(df['error'].corr(df['PLEC'], method='pearson')),
      '\nKendall method: \t {0}'.format(df['error'].corr(df['PLEC'], method='kendall')),
      '\nSpearman method: \t {0}'.format(df['error'].corr(df['PLEC'], method='spearman')))

=== Correlation measures between error column and gender column === 
Pearson method: 	 0.02431993830757109 
Kendall method: 	 0.016038513898141937 
Spearman method: 	 0.01789272694046741


<b>6. One-hot Encoder used to encode values in a 'woj' column (voivodeship of the responder).</b>

In [131]:
one_hot_encoder = OneHotEncoder(categories='auto')
one_hot_encoder.fit(df['woj'].unique().reshape(-1, 1))

one_hot_encoded_voivodeship = one_hot_encoder.transform(df['woj'].to_numpy().reshape(-1, 1)).toarray()

print(one_hot_encoded_voivodeship[: 5])
df.head()

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]


URODZONY  PLEC  KLM6  woj  q9  q10  q11  q12   q13  q14  ...  q154  q155  \
0      1940     2     1   11   2    4  NaN   13   8.0    1  ...     2   NaN   
1      1943     1     3   11   8    4  NaN   13   3.0    1  ...     2   NaN   
2      1936     1     3   11   8    4  NaN   13   3.0    1  ...     2   NaN   
3      1948     1     3   11   4    4  NaN   13   6.0    1  ...     2   NaN   
4      1994     2     1   10   3    4  NaN   11  11.0    2  ...     1   2.0   

   q156  r7s1  r7s2  r7s3  r7s4  r7s5      waga  error  
0     2  2012     7     4    18    42  0.722004   -4.0  
1     2  2012     7     4    16    43  0.686766   -1.0  
2     1  2012     7     4    18    16  0.686766   -1.0  
3     2  2012     7     4    19    43  1.604806    3.0  
4     1  2012     7     5    11    17  1.316088   -1.0  

[5 rows x 267 columns]

<b>7. Describe 5 columns showing number of each value occurences, number of NA values, mean, median, quartiles, max and min (if possible).</b> 

In [132]:
def describe_quantitative_column(column, column_name):
    print('=== {0} column description ==='.format(column_name),
          '\nNA values  {0}'.format(column.isna().sum()),
          '\nvar \t  {0}'.format(np.nanvar(column)),
          '\n{0}'.format(column.describe()),
          '\nValue  count\n{0}\n'.format(column.value_counts()))

def describe_qualitative_column(column, column_name):
    print('=== {0} column description ==='.format(column_name),
          '\nNA values  {0}'.format(column.isna().sum()),
          '\nValue  count\n{0}\n'.format(column.value_counts()))

def describe_opinion_column(column, column_name):
    print('=== {0} column description ==='.format(column_name),
          '\nNA values  {0}'.format(column.isna().sum()),
          '\nNot-sure values\t{0}'.format(column[column > 11].count()),
          '\nvar \t  {0}'.format(np.nanvar(column[column < 12])),
          '\n{0}'.format(column[column < 12].describe()),
          '\nValue  count\n{0}\n'.format(column.value_counts()))
    
def describe_education_column(column, column_name):
    print('=== {0} column description ==='.format(column_name),
          '\nNA values  {0}'.format(column.isna().sum()),
          '\n{0}'.format(column.quantile([.25, .5, .75])),
          '\nValue  count\n{0}\n'.format(column.value_counts()))
    
describe_quantitative_column(df['error'], 'Prediction error')
describe_qualitative_column(df['woj'], 'Voivodeship')
describe_education_column(df['q9'], 'Education')
describe_opinion_column(df['q38s14'], 'Opinion about Sławomir Nowak')
describe_opinion_column(df['q38s21'], 'Opinion about Andrzej Seremet')

=== Prediction error column description === 
NA values  0 
var 	  10.81998263888889 
count    960.000000
mean      -1.220833
std        3.291089
min      -10.000000
25%       -3.000000
50%       -1.000000
75%       -1.000000
max       39.000000
Name: error, dtype: float64 
Value  count
-1.0     473
 1.0      86
 4.0      76
-3.0      71
-6.0      62
-4.0      34
 0.0      30
-5.0      25
-8.0      21
-7.0      20
 3.0      15
 2.0      13
 9.0       8
-2.0       8
-9.0       7
-10.0      6
 5.0       3
 7.0       1
 39.0      1
Name: error, dtype: int64

=== Voivodeship column description === 
NA values  0 
Value  count
7     125
12    123
15     96
6      73
5      62
1      60
9      58
11     57
3      57
2      56
16     51
14     39
13     35
4      28
8      22
10     18
Name: woj, dtype: int64

=== Education column description === 
NA values  0 
0.25    4.0
0.50    6.0
0.75    8.0
Name: q9, dtype: float64 
Value  count
4     230
8     154
2     147
11    145
6      95
7      53


<b>8. Get the rows which 'q98' column equals 1 and 'q101' column equals 2.</b>

In [133]:
print(df[(df['q98'] == 1) & (df['q101'] == 2)][['q98', 'q101']],
      '\n')
df[(df['q98'] == 1) & (df['q101'] == 2)]

     q98  q101
3      1     2
6      1     2
9      1     2
10     1     2
16     1     2
19     1     2
21     1     2
23     1     2
24     1     2
26     1     2
28     1     2
31     1     2
43     1     2
44     1     2
46     1     2
47     1     2
48     1     2
51     1     2
52     1     2
53     1     2
54     1     2
60     1     2
63     1     2
64     1     2
70     1     2
71     1     2
73     1     2
79     1     2
81     1     2
84     1     2
..   ...   ...
842    1     2
848    1     2
852    1     2
854    1     2
867    1     2
868    1     2
869    1     2
870    1     2
872    1     2
878    1     2
879    1     2
884    1     2
885    1     2
887    1     2
890    1     2
891    1     2
895    1     2
899    1     2
901    1     2
902    1     2
908    1     2
916    1     2
919    1     2
921    1     2
923    1     2
927    1     2
928    1     2
937    1     2
943    1     2
959    1     2

[246 rows x 2 columns] 



URODZONY  PLEC  KLM6  woj  q9  q10  q11  q12   q13  q14  ...  q154  q155  \
3        1948     1     3   11   4    4  NaN   13   6.0    1  ...     2   NaN   
6        1979     2     5   12   5    1  3.0    3   NaN    2  ...     2   NaN   
9        1976     1     4    9  11    1  3.0    4   NaN    2  ...     2   NaN   
10       1981     1     6   15   1    4  NaN   12   7.0    1  ...     2   NaN   
16       1944     2     5   12   4    4  NaN   13   6.0    1  ...     2   NaN   
19       1970     1     5    1   7    1  1.0    6   NaN    2  ...     2   NaN   
21       1984     2     3   12  11    4  NaN   14   4.0    2  ...     2   NaN   
23       1937     1     3   12   2    4  NaN   13   6.0    1  ...     2   NaN   
24       1950     1     4   12   4    4  NaN   12   6.0    1  ...     2   NaN   
26       1951     2     3   12   8    4  NaN   13   4.0    1  ...     2   NaN   
28       1961     2     3    7   2    4  NaN   14   7.0    2  ...     2   NaN   
31       1961     1     2   15   8    3  3.0    7   NaN    2  ...     2   NaN   
43       1989     2     1   16   2    4  NaN   16   8.0    2  ...     2   NaN   
44       1963     1     1   16   8    1  1.0    2   NaN    2  ...     1   1.0   
46       1959     1     5   12   4    1  3.0    6   NaN    2  ...     2   NaN   
47       1948     1     5   12   4    4  NaN   13   6.0    1  ...     2   NaN   
48       1971     1     6    5   2    3  3.0    6   NaN    2  ...     2   NaN   
51       1979     1     3   15   9    1  1.0    3   NaN    2  ...     2   NaN   
52       1986     1     6    5   5    1  3.0    6   NaN    2  ...     2   NaN   
53       1955     2     6    5   8    4  NaN   12   4.0    1  ...     2   NaN   
54       1960     2     6    5   4    1  3.0    5   NaN    2  ...     2   NaN   
60       1958     2     3    5   9    1  1.0    3   NaN    2  ...     2   NaN   
63       1958     2     3    6   4    1  1.0    6   NaN    2  ...     2   NaN   
64       1974     2     3    6   6    4  NaN   14   4.0    2  ...     2   NaN   
70       1956     1     1    1   4    1  3.0    6   NaN    2  ...     2   NaN   
71       1987     1     1    1   3    3  3.0    7   NaN    2  ...     2   NaN   
73       1978     2     6    7   5    4  NaN   14   5.0    2  ...     2   NaN   
79       1960     1     6   15   7    4  NaN   14   5.0    2  ...     2   NaN   
81       1987     2     1    1   6    1  3.0    4   NaN    2  ...     2   NaN   
84       1958     2     2    4   5    3  3.0   15   7.0    2  ...     2   NaN   
..        ...   ...   ...  ...  ..  ...  ...  ...   ...  ...  ...   ...   ...   
842      1951     1     4   15   6    4  NaN   13   3.0    1  ...     2   NaN   
848      1977     1     5   16   5    1  3.0    3   NaN    2  ...     2   NaN   
852      1969     1     1   12   4    4  NaN   12   5.0    1  ...     2   NaN   
854      1969     1     1   12   4    1  3.0    5   NaN    2  ...     2   NaN   
867      1961     1     5   12   4    4  NaN   13   8.0    1  ...     2   NaN   
868      1940     1     5    2   2    4  NaN   13   6.0    2  ...     2   NaN   
869      1950     2     5    2   6    4  NaN   13   4.0    1  ...     2   NaN   
870      1961     2     5    2   8    1  2.0    4   NaN    2  ...     2   NaN   
872      1961     2     5    2   2    1  1.0    6   NaN    2  ...     2   NaN   
878      1977     2     2   12   6    1  3.0    4   NaN    2  ...     2   NaN   
879      1953     1     2   12   7    4  NaN   13   6.0    1  ...     2   NaN   
884      1971     1     2   16   2    4  NaN   14   6.0    2  ...     2   NaN   
885      1992     1     2   16   4    4  NaN   14   8.0    2  ...     2   NaN   
887      1987     1     2   16   3    1  2.0    6   NaN    2  ...     2   NaN   
890      1959     2     5    2   8    4  NaN    4   NaN    1  ...     2   NaN   
891      1988     1     6    5  10    4  NaN   11  11.0    2  ...     2   NaN   
895      1949     1     5   12   4    4  NaN   14   6.0    2  ...     2   NaN   
899      1993     1     5   12   3  

<b>9. Create 3 more columns, which are combinations of existing columns.</b>

In [134]:
# column showing year of a responder depending on its' birth date
# column showing decade of a responder depending on its' birth date
# column showing day of the week when responder was born depending on its' birth date

# column showing combination of q24s1 and q25s1 columns (political situation in Poland)
# column showing combination of q24s2 and q25s2 columns (economical situation in Poland)
# column showing combination of q24s3 and q25s3 columns (situation in responder's workplace)

# column showing combination of q33, q34, q35 and q36 columns (opinion about Donald Tusk's government)
# column showing combination of q38s1, q38s2, q38s3, q38s4(Jacek Cichocki?), q38s9, q38s10, q38s13, q38s14, q38s17, q38s19(Marek Sawicki?), q38s20, q38s21(Andrzej Seremet?), q38s22, q38s23, q38s24(Bogdan Zdrojewski?) (opinion about politics of the ruling party)

# column showing combination of q65s1, q65s2, q65s3, q65s4 (opinion about muslims)
# column showing combination of q67s1, q67s2, q67s3, q67s4 (opinion about buddhists)
# column showing combination of q68s1, q68s2, q68s3, q68s4 (opinion about Jehowa witnesses)
# column showing combination of q69s1, q69s2, q69s3, q69s4 (opinion about Hare Krishna zealots)

<b>10. Save DataFrame to a csv file.</b>

In [135]:
df.to_csv('igrzyska_list_7.csv')